services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: eduplatform-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./seeds:/seeds:ro
    environment:
      MONGO_INITDB_DATABASE: eduplatform
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet 2>/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
